services:
  ci_server:
    build: .
    privileged: true
    ports:
      - "8090:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - production-network

networks:
  production-network:
    driver: host