services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8090:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge
