version: '3.8'

services:
  web:
    build: .
    container_name: simple_python_web
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080:5000"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

